version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/tmp

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install dependencies
      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Check out gh-pages
      - run:
          name: Check out
          command: git checkout --orphan gh-pages

      # Build
      - run:
          name: Build
          command: yarn run build

      # Deploy
      - run:
          name: Deploy
          command: |
            git reset
            git add .circleci/
            git add -f dist/
            git add index.html
            git config --global user.name "Saori"
            git config --global user.email "Saori@users.noreply.github.com"
            git commit -m ":green_heart: CI build"
            git push -f origin gh-pages
